"$schema" = 'https://starship.rs/config-schema.json'

add_newline = false

format = """
$username\
$hostname\
$localip\
$directory\
$vcsh\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$hg_branch\
$docker_context\
$memory_usage\
$env_var\
$sudo\
$cmd_duration\
$jobs\
$battery\
$time\
$status\
$shell
$character"""

[directory]
truncate_to_repo = false
truncation_length = 0

[git_metrics]
disabled = false

[memory_usage]
disabled = false
