return {
    "nvim-lua/plenary.nvim",
    "tpope/vim-repeat",
    "tpope/vim-rsi",
    "wellle/targets.vim",
    "ggandor/lightspeed.nvim",
    "stevearc/dressing.nvim",
    "vim-scripts/restore_view.vim",
    "vim-scripts/ReplaceWithRegister",
    "nvim-tree/nvim-web-devicons",
    "behzade/lf.nvim",
    'nvim-pack/nvim-spectre',
    "vrischmann/tree-sitter-templ",
    "numToStr/Comment.nvim",
}
